### Drill 10.7.1 - Query, slicing, combining arrays

<h4>Let&rsquo;s create a 5 x 3 array using NumPy</h4>.  We want to shape it with five rows and three columns in each row.  Use NumPy&rsquo;s <code>random.seed(15)</code> to start ...  But note there are differences in version.  Check out the depreciated statements below.


In [51]:
#[answer]
import numpy as np

myArray1 = np.random.random_integers(15, size=15).reshape((5,3))
# note that the above syntax is depreciated.
# instead use np.random.randint(7, size=(5,3))
myArray2 = np.random.randint(7, size=(5, 3))

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 15 + 1) instead
  after removing the cwd from sys.path.


In [11]:
print(myArray1)
print("-"*60)
print(myArray2)

[[14 15  3]
 [ 4  3  8]
 [11  4  1]
 [11 12  1]
 [ 7 14  4]]
------------------------------------------------------------
[[2 1 6]
 [2 3 6]
 [2 3 0]
 [0 0 2]
 [6 4 1]]


### manipulating NumPy arrays

Create a random arrays of integers.  Next we&rsquo;ll try to pull out data from this multidimensional array.  First, let&rsquo;s try to grab all the data using the colon operator for the first 5 items.  What appears?  We're going to explore multidimensional arrays.

In [33]:
#  
import numpy as np
ar1 = np.random.randint(7, size=(5, 3))
# let's view the entire array
print("-"*60)
print(ar1)
# what happens when we call only "0"?
print("-"*60, "\nar1[0]")
print(ar1[0])
# what if we try the range :5?
print("-"*60, "\nar1[:5]")
print(ar1[:5])

------------------------------------------------------------
[[0 3 0]
 [3 1 5]
 [6 4 1]
 [5 6 0]
 [6 4 5]]
------------------------------------------------------------ 
ar1[0]
[0 3 0]
------------------------------------------------------------ 
ar1[:5]
[[0 3 0]
 [3 1 5]
 [6 4 1]
 [5 6 0]
 [6 4 5]]


#### More experiments with slicing a 2D arrays.

In [34]:
### 
# using ar1, how to retrieve all the values?
print(ar1[:])
print("-"*60)
# how about a range of values?  
# must identify the x, y  (Example: all the rows, except col 1 and 2)
print(ar1[:,1:3])  

[[0 3 0]
 [3 1 5]
 [6 4 1]
 [5 6 0]
 [6 4 5]]
------------------------------------------------------------
[[3 0]
 [1 5]
 [4 1]
 [6 0]
 [4 5]]


We can select a <font color='red'>subset</font> of rows and columns in the [ ].  The left-most operator we&rsquo;re using <font color='red'>:</font> for &ldquo;all&rdquo; and operates on the rows. The range after the comma, e.g., 1:3] operaters on the columns. 
Using the <code>ar1</code> created above, let&rsquo;s swap the row/column operators.  Try it.

In [35]:
print(ar1[1:3, :])

[[3 1 5]
 [6 4 1]]


What if we want to grab the rows in steps of 2 and the columns in steps of 2?
What might it show us?  (e.g., ar1[::2, ::2]).  Replace the 2 with different values to see what you get as output.


In [36]:
print(ar1[::2, ::2])

[[0 0]
 [6 1]
 [6 5]]


#### Experiment with vstack (any iterable - stacking the data vertically).

In [43]:
ar1 = np.random.randint(7, size=(5, 3))
ar2 = np.random.randint(7, size=(5, 3))
print(("-"*60),"\n", ar1)
print(("-"*60),"\n", ar2)
print(("-"*60),"\nVertical Stack:\n", np.vstack([ar1, ar2]))

------------------------------------------------------------ 
 [[6 5 0]
 [6 0 3]
 [5 4 3]
 [6 1 3]
 [0 5 1]]
------------------------------------------------------------ 
 [[2 0 3]
 [6 1 4]
 [1 0 1]
 [1 3 1]
 [4 2 2]]
------------------------------------------------------------ 
Vertical Stack
 [[6 5 0]
 [6 0 3]
 [5 4 3]
 [6 1 3]
 [0 5 1]
 [2 0 3]
 [6 1 4]
 [1 0 1]
 [1 3 1]
 [4 2 2]]


Sometimes we need to <font color='red'>reshape</font> the array ... let&rsquo;s reshape <code>ar1</code> from 5 rows and three columns to three rows and five columns.

In [44]:
print(ar1.reshape(3,5))

[[6 5 0 6 0]
 [3 5 4 3 6]
 [1 3 0 5 1]]


If we can stack <i>vertically</i> perhaps horizontally, too?

In [50]:
ar1 = np.random.randint(7, size=(5, 3))
ar2 = np.random.randint(7, size=(5, 3))
print(("-"*60),"\n", ar1)
print(("-"*60),"\n", ar2)
print(("-"*60),"\nHorizontal Stack:\n", np.hstack([ar1, ar2]))

------------------------------------------------------------ 
 [[1 1 6]
 [0 5 5]
 [6 3 6]
 [3 4 3]
 [4 4 0]]
------------------------------------------------------------ 
 [[5 0 5]
 [2 5 5]
 [4 5 3]
 [5 2 4]
 [2 6 0]]
------------------------------------------------------------ 
Horizontal Stack:
 [[1 1 6 5 0 5]
 [0 5 5 2 5 5]
 [6 3 6 4 5 3]
 [3 4 3 5 2 4]
 [4 4 0 2 6 0]]


In [49]:
#### Concatenation of lots of arrays?
np.vstack((ar1 for x in range(5)))

array([[6, 4, 0],
       [4, 6, 1],
       [1, 1, 0],
       [6, 4, 0],
       [3, 5, 5],
       [6, 4, 0],
       [4, 6, 1],
       [1, 1, 0],
       [6, 4, 0],
       [3, 5, 5],
       [6, 4, 0],
       [4, 6, 1],
       [1, 1, 0],
       [6, 4, 0],
       [3, 5, 5],
       [6, 4, 0],
       [4, 6, 1],
       [1, 1, 0],
       [6, 4, 0],
       [3, 5, 5],
       [6, 4, 0],
       [4, 6, 1],
       [1, 1, 0],
       [6, 4, 0],
       [3, 5, 5]])

#### Concatenation... 
Using our <code>ar1</code> and <code>ar2</code>, let&rsquo;s concatenate them, experimenting on the axis (1 or 0).   First, let's try on axis = 1.  What do you see?  Next try axis = 0 and compare.

&#x1f601; Pretty cool, no? &#x1f638;

In [61]:
np.concatenate((ar1, ar2), axis=1)

array([[1, 1, 6],
       [0, 5, 5],
       [6, 3, 6],
       [3, 4, 3],
       [4, 4, 0],
       [5, 0, 5],
       [2, 5, 5],
       [4, 5, 3],
       [5, 2, 4],
       [2, 6, 0]])

In [63]:
#And on axis = 0:
np.concatenate((ar2, ar1), axis=0)

array([[5, 0, 5],
       [2, 5, 5],
       [4, 5, 3],
       [5, 2, 4],
       [2, 6, 0],
       [1, 1, 6],
       [0, 5, 5],
       [6, 3, 6],
       [3, 4, 3],
       [4, 4, 0]])

### Splitting Arrays
This practice splits arrays.  Using <code>a1</code> let&rsquo;s dstack and split ... 

In [66]:
ar3 = np.dstack((ar1,ar1))
ar3

array([[[1, 1],
        [1, 1],
        [6, 6]],

       [[0, 0],
        [5, 5],
        [5, 5]],

       [[6, 6],
        [3, 3],
        [6, 6]],

       [[3, 3],
        [4, 4],
        [3, 3]],

       [[4, 4],
        [4, 4],
        [0, 0]]])

Let&rsquo;s <font color='red'>split</font>!  It undoes what we do with the dstack (or reduce the dimension)... for example by 1.


In [69]:
ar3 = np.dstack((ar1, ar1))
ar3

array([[[1, 1],
        [1, 1],
        [6, 6]],

       [[0, 0],
        [5, 5],
        [5, 5]],

       [[6, 6],
        [3, 3],
        [6, 6]],

       [[3, 3],
        [4, 4],
        [3, 3]],

       [[4, 4],
        [4, 4],
        [0, 0]]])

<h5>hsplit and vsplit</h5>


In [76]:
# take a look at ar2 and let's split and see the results.
# using hsplit first, what do you see?
np.hsplit(ar2,3)
# replace the ,3 above with ,2 and see... 
# there will be an error when the array cannot be divided evenly.
# using vsplit here will result in an error.  Good luck!

[array([[[1]],
 
        [[0]],
 
        [[6]],
 
        [[3]],
 
        [[4]]]), array([[[1]],
 
        [[5]],
 
        [[3]],
 
        [[4]],
 
        [[4]]]), array([[[6]],
 
        [[5]],
 
        [[6]],
 
        [[3]],
 
        [[0]]])]