<h3>Drill 10.6.1</h3> <ul><li>Vectorization</li><li>Multidimensional Arrays</li></ul><hr >
<blockquote>These operations act upon entire set of values instead of individual items, making it a high-level programming model ... working on <i>aggregates</i>. </blockquote>

In [4]:
#V ectorization helps us process lots of data quickly...  
# Given a random array, let's square it. ... quickly.
import numpy as np
npArray = np.myArray2 = np.random.randint(7, size=(5, 3))
npArray * 2

array([[ 8,  6,  6],
       [ 4, 10,  6],
       [ 4,  8,  4],
       [10,  0,  6],
       [12,  8,  6]])

Notice we can seemingly chain behaviors ... first square each value and then divide it by .5. (Why? Who knows! (grin))  Instead of using a <code>for loop</code> or some other technique, using NumPy allows us to write concise, fast-operating code.
<code>npArray ** 2 / .05</code>

In [9]:
npArray ** 2 / .05

array([[320., 180., 180.],
       [ 80., 500., 180.],
       [ 80., 320.,  80.],
       [500.,   0., 180.],
       [720., 320., 180.]])

In practice we might need to transform a bunch of data.  For instance, when data values between objects or phenomenon of interest are really close or small, we could do a log transformation on the data.  This is a common technique in data visualization.  So, let&rsquo;s say we have an array (myArray) ... let&rsquo;s transform the values by some rule (say the log).
Using the <code>math</code> library ... let&rsquo;s apply a base<sub>2</sub> log to all the values in the array, npArray.

In [15]:
import math
import numpy as np

newArray = np.random.randint(7, size=(5, 3))

def makeLog(val):
    return (math.log(val,2))

makeLog(3)
# for this example, we are not passing the array but rather a value
# from the array.

1.5849625007211563

### multidimensional arrays ...

In [1]:
# for practice's sake, as described in the asynch, 
# let's create a 5 x 5 array
import numpy as np
fiveByFiveArray = np.random.randint(5, size=(5,5))
print(fiveByFiveArray)

[[3 3 0 4 4]
 [0 1 2 1 3]
 [1 4 1 3 0]
 [4 0 3 2 0]
 [1 2 3 0 0]]


Let&rsquo;s confirm the shape ... try <code>.shape</code>

In [2]:
fiveByFiveArray.shape

(5, 5)

When determining what data to select for further processing, you might want to look for some criteria.  In this example, say we want to find the minimum value of a data set.  (e.g., we're integrating lots of data files and we're checking for what data groups to ignore)...

In [24]:
# what's the minimum value in this array?
newArray.min()

0

In [25]:
# what's the max?
newArray.max()

5

In [26]:
# cool ... what's the variance of all these cool data?
newArray.var()

2.1066666666666665

A cool thing to do is to multiple arrays together ... 
Since we have 2 arrays already [fiveByFiveArray and npArray], let's see what happens when we multiply them.  [It won't work 'cause one is 5x5 and the other is 5x3.]

In [28]:
npArray * fiveByFiveArray

ValueError: operands could not be broadcast together with shapes (5,3) (5,5) 

So, let's create two arrays of the same size and then multiply them.

In [32]:
import numpy as np
t1 = np.random.randint(7, size=(5, 3))
t2 = np.random.randint(7, size=(5, 3))
t3 = t1 * t2
print(t3)

[[24  4  8]
 [16  3  0]
 [ 4  6 12]
 [18 12  3]
 [ 5  6  8]]


<h6>Other ideas...</h6>  Ravel?

In [34]:
raveled = t1.ravel()
print(raveled)

[4 2 4 4 1 3 1 2 2 6 6 1 5 6 4]


In [35]:
#flattening?  Yes, let's see what happens when flatten a 5x5 into a one-dimensional list
print(t1.flatten())
