### Drill: Query, Slicing, Combining arrays

- Run the first cell to create two 5x3 integer arrays

In [1]:
import numpy as np

np.random.seed(15)

ar1 = np.random.randint(15, size=(5, 3))
ar2 = np.random.randint(7, size=(5, 3))

In [2]:
# printout of the two arrays made above
print(ar1)
print("-" * 60)
print(ar2)

[[ 8  5 12]
 [ 5  7  0]
 [12 11  7]
 [11  5  6]
 [13  1 13]]
------------------------------------------------------------
[[0 6 2]
 [4 1 5]
 [3 4 5]
 [4 5 6]
 [0 2 1]]


<h3>Slicing NumPy arrays</h3>

We can select a <font color='red'>subset</font> of rows and columns in the [ ]. The left-most operator operates on the rows (just a colon selects all rows). The range after the comma operates on the columns (e.g.[, 1:3] select columns 1 & 2). 
```
ar[:,1:3]
```

From the arrays created above:

- Use [] slicing to print out the last 2 rows of ```ar1```
- Use [] slicing to print out the first column of `ar2`

In [3]:
# [Answer]

In [ ]:
# [Answer]

- Use [] slicing to print out the row 2 and columns 2 & 3 from `ar1`
- Use [] slicing to print out the last 2 rows and last column of `ar2`

In [4]:
# [Answer] 

In [ ]:
# [Answer]

- Use [] slicing to print out the first element of `ar1`
- Use [] slicing to print out the last element of `ar2`

In [5]:
# [Answer]

In [ ]:
# [Answer]

#### Stacking array
- Use vstack and hstack on the two arrays ar1 and ar2
- What's the result?

In [6]:
# [Answer] vstack

In [7]:
# [Answer] hstack

#### Concatenation... 
Using our <code>ar1</code> and <code>ar2</code>, let&rsquo;s concatenate them, experimenting on the axis (1 or 0).   First, let's try on axis = 1.  What do you see?  Next try axis = 0 and compare.

&#x1f601; Pretty cool, no? &#x1f638;
- Whats the difference between concatenate aand v/hstack?

In [8]:
# [Answer] on axis = 1:

In [9]:
# [Answer] on axis = 0:

##### Splitting Arrays
To split an array into multiple smaller sub-arrays - use np.split()
- Split array ```ar1``` into 5 arrays 

In [10]:
# [Answer]